services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - ./prometheus/targets:/etc/prometheus/targets:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
    networks:      
      - webservices
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - webservices
      - default
    environment:
      GF_SERVER_ROOT_URL: "https://${MONITORING_DOMAIN_PUBLIC}"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PWD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${MONITORING_DOMAIN_PUBLIC}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=webservices"
      - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
     - "--docker_only=true"
     - "--housekeeping_interval=30s"
     - "--store_container_labels=true"

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    command:
      - "--config.file=/etc/blackbox_exporter/config.yml"

  fritz_exporter:
    image: pdreker/fritz_exporter:2
    restart: always
    environment:
      FRITZ_HOSTNAME: 'fritz.box'
      FRITZ_USERNAME: 'prometheus'
      FRITZ_PASSWORD: 'prompassword'
      FRITZ_HOST_INFO: true
    ports:
      - "9787:9787"
    
  snmp_exporter:
    image: prom/snmp-exporter:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/snmp/:/etc/snmp_exporter/:ro
    command:
      - '--config.file=/etc/snmp_exporter/*.yml'

  imap_exporter:
    image: ghcr.io/jasminemoeller/imap-exporter:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/targets/imap-exporter/config.yml:/app/config.yml:ro



networks:
  webservices:
    external: true

volumes:
  prometheus_data:
  grafana_data:
