global:
    scrape_interval: 1m
    evaluation_interval: 1m
    external_labels:
        monitor: 'prometheus-monitoring'

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # 1) Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 2) Host metrics via node_exporter
  - job_name: 'nodes'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/nodes/*.yml'


  # 3) Docker/container metrics via cAdvisor
  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/cadvisor/*.yml'
    metric_relabel_configs:
      - source_labels: ['container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['name']
        target_label: 'container'

  # 4) Edgerouter via SNMP
  - job_name: 'edgerouter'
    static_configs:
      - targets:
        - 192.168.x.x  # Your EdgeRouter IP
        labels:
          hostname: 'edgerouter'
    metrics_path: /snmp
    params:
      module: edgerouter
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116


